version: '3.9'

services:
  database:
    container_name: wealthwise-database
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: wealthwise-app
    image: sergiofelixdev/wealthwise:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    restart: on-failure
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRINT_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - database

volumes:
  postgres-data:
